<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rte_plus"
 *
 * Auto generated by Extension Builder 2016-04-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Additional RTE Features',
	'description' => 'Adds features like \"track changes\" to rtehtmlarea (working with <del> and <ins> tags including timestamps)',
	'category' => 'fe',
	'author' => 'Jochen Rieger, Kai Groetenhardt',
	'author_email' => 'typo3@connecta.ag',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);